server:
  #cambio para multiples instancias.Que lo coja dinamicamente
  #port: 8001
  #PONEMOS PORT 0 para que se busquen los puertos libres en el entorno donde se aloja el  microserv.De entre los puertos libres se asignar치 uno aleatoriamente
  #https://www.youtube.com/watch?list=PL4bT56Uw3S4yTSw5Cg1-mhgoS85fVeFkT&t=277&v=q5Qsj8ogeqU&feature=youtu.be
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:    
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance: 
      #Para multiples inst.Para que sea din치mico el bind 
      #hostname: localhost - Ya no nos vale.Debe ser din치mico
      #${spring.application.name} - Bind service
      #${spring.application.instance_id:${random.value}} Para multiples instancias, si tengo varias no pueden llamarse igual.Se asignar치 aleatroiamente
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
resilience4j.circuitbreaker:
    instances:
        carsCB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10          
        bikesCB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 20
            waitDurationInOpenState: 50s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
        allCB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 20
            waitDurationInOpenState: 50s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
spring:
  application:
    zipkin: htpp://localhost:9411
management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3                  