#Se debe arrancar primero el config-server
server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/abarqueror/microservices-tutorial
          search-paths: config-data
  application:
    name: config-service
